### ISSUE TITLE
회원가입 / 회원정보수정

### ISSUE THREAD

**Issue by zuminzi** [likelion-backendschool/FinalProject_JuMinJi_team7#1]
## Requests
- 회원가입
- 회원 정보 수정
## Request Details
- 회원은 일반회원과 작가회원이 있다.
- 가입 직후는 일반회원이고, 작가명 등록을 하면 작가회원이 된다. (회원정보 수정페이지에서도 동일하게 적용)
- 작가회원이 되면 상품(책)을 등록할 수 있다.
- 별개로 authLevel 의 값이 7이면 관리자의 역할도 수행할 수 있다.
- 회원가입시 축하메일을 발송한다.
## Todo
- [x] Member 엔티티 설계
- [x] layout 구현
- [x] SMTP 서버 설정 및 메일 전송 base 작업
- [x] 회원가입 구현
- [x] 권한별 MemberService 구현
- [x] 회원정보 수정 구현

**Comment by SG1515** [comment]
request, request detail, To do 방식으로 체계적으로 한 것이 좋네요!!
소망님 md 파일과 마찬가지로 이런 방식들을 사용해서 정리하면서 해야겠습니다 ㅠㅠ
제 레포에서 짠다음에 가져와서 다른분들이 더 보기도 어렵게 되었는데
여튼, 이슈 발행할 때 이런식으로 하는 것도 좋겠네요!!
