### ISSUE TITLE
JWT 로그인, REST API

### ISSUE THREAD

**Issue by zuminzi** [likelion-backendschool/FinalProject_JuMinJi_team7#21]
## Todo List
- [x] JWT 로그인 구현(POST /api/v1/member/login)
- [x] 내 도서 리스트 구현(GET /api/v1/myBooks) -> **_need to fix_**(**요구사항에 맞게 외래키까지 리턴**) -> **resolved**
- [x] 내 도서 상세정보 구현(GET /api/v1/myBooks/{id}) -> **_need to fix_**(**요구사항에 맞게 외래키까지 리턴**) -> **resolved**
- [x] 로그인 한 회원의 정보 구현(GET /api/v1/member/me)
- [x] Srping Doc 으로 API 문서화(크롬 /swagger-ui/index.html )

### `GET /api/v1/myBooks`
- 로그인 필요
- 현재 로그인한 회원이 소유한 책정보들을 리스팅
- 현재 1번 회원이 로그인 되었다고 가정
    - 로그인 방식은 JWT 엑세스 토큰
 ```javascript
{
  "resultCode": "S-1",
  "msg": "성공",
  "data": {
    "myBooks": [
      {
        "id": 4,
        "createDate": [
          2022,
          11,
          3,
          17,
          3,
          22,
          162538000
        ],
        "modifyDate": [
          2022,
          11,
          3,
          17,
          3,
          22,
          162538000
        ],
        "ownerId": 2,
        "product": {
          "id": 3,
          "createDate": [
            2022,
            11,
            3,
            17,
            3,
            22,
            62061000
          ],
          "modifyDate": [
            2022,
            11,
            3,
            17,
            3,
            22,
            62061000
          ],
          "authorId": 1,
          "authorName": "user1",
          "subject": "상품명3"
        }
      },
      {
        "id": 5,
        "createDate": [
          2022,
          11,
          3,
          17,
          3,
          22,
          162538000
        ],
        "modifyDate": [
          2022,
          11,
          3,
          17,
          3,
          22,
          162538000
        ],
        "ownerId": 2,
        "product": {
          "id": 4,
          "createDate": [
            2022,
            11,
            3,
            17,
            3,
            22,
            66057000
          ],
          "modifyDate": [
            2022,
            11,
            3,
            17,
            3,
            22,
            66057000
          ],
          "authorId": 2,
          "authorName": "홍길순",
          "subject": "상품명4"
        }
      }
    ]
  },
  "fail": false,
  "success": true
}
```
### `GET /api/v1/myBooks/{myBookId}`
- 로그인 필요
```javascript
{
  "resultCode": "S-1",
  "msg": "성공",
  "data": {
    "myBook": {
      "id": 3,
      "createDate": [
        2022,
        11,
        3,
        17,
        21,
        5,
        730612000
      ],
      "modifyDate": [
        2022,
        11,
        3,
        17,
        21,
        5,
        730612000
      ],
      "ownerId": 1,
      "product": {
        "id": 5,
        "createDate": [
          2022,
          11,
          3,
          17,
          21,
          5,
          625079000
        ],
        "modifyDate": [
          2022,
          11,
          3,
          17,
          21,
          5,
          625079000
        ],
        "authorId": 1,
        "authorName": "user1",
        "subject": "상품명5",
        "bookChapters": [
          {
            "id": 6,
            "subject": "제목 6",
            "content": "내용 6",
            "contentHtml": "내용 6"
          },
          {
            "id": 5,
            "subject": "제목 5",
            "content": "내용 5",
            "contentHtml": "내용 5"
          },
          {
            "id": 2,
            "subject": "자바스크립트를 우아하게 사용하는 방법",
            "content": "# 자바스크립트는 이렇게 쓰세요.\n\n```js\nconst a = 10;\nconsole.log(a);\n```\n",
            "contentHtml": "<h1>자바스크립트는 이렇게 쓰세요.</h1><div data-language=\"js\" class=\"toastui-editor-ww-code-block-highlighting\"><pre class=\"language-js\"><code data-language=\"js\" class=\"language-js\"><span class=\"token keyword\">const</span> a <span class=\"token operator\">=</span> <span class=\"token number\">10</span><span class=\"token punctuation\">;</span>\n<span class=\"token console class-name\">console</span><span class=\"token punctuation\">.</span><span class=\"token method function property-access\">log</span><span class=\"token punctuation\">(</span>a<span class=\"token punctuation\">)</span><span class=\"token punctuation\">;</span></code></pre></div>\n"
          },
          {
            "id": 1,
            "subject": "자바를 우아하게 사용하는 방법",
            "content": "# 내용 1",
            "contentHtml": "<h1>내용 1</h1>"
          }
        ]
      }
    }
  },
  "fail": false,
  "success": true
}
```
### ` POST /api/v1/member/login`
- username과 password 를 입력하면 그에 해당하는 accessToken 을 생성
```javascript
{
  "resultCode": "S-1",
  "msg": "로그인 성공, Access Token을 발급합니다.",
  "data": {
    "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJib2R5Ijoie1wiaWRcIjoyLFwiY3JlYXRlRGF0ZVwiOlsyMDIyLDExLDMsMTcsMywyMSw5NTk0MzAwMDBdLFwibW9kaWZ5RGF0ZVwiOlsyMDIyLDExLDMsMTcsMywyMiwxNjI1MzgwMDBdLFwidXNlcm5hbWVcIjpcInVzZXIyXCIsXCJlbWFpbFwiOlwidXNlcjJAdGVzdC5jb21cIixcImVtYWlsVmVyaWZpZWRcIjpmYWxzZSxcIm5pY2tuYW1lXCI6XCLtmY3quLjsiJxcIixcImF1dGhMZXZlbFwiOlwiTk9STUFMXCIsXCJhdXRob3JpdGllc1wiOlt7XCJhdXRob3JpdHlcIjpcIk1FTUJFUlwifSx7XCJhdXRob3JpdHlcIjpcIkFVVEhPUlwifV19IiwiZXhwIjo0ODIxMDYyNzcxfQ.LinAN3u8IrXSzJejLCYKMQE84LMWOOzbfi0giVoN647ciodIXMT1TvLq0oxIPs-fD0ZdBRUikt_jq193bgyFeg"
  },
  "fail": false,
  "success": true
}
```
### `GET /api/v1/member/me`
- 로그인 필요
- 현재 로그인된 회원의 정보를 출력
```javascript
{
  "resultCode": "S-1",
  "msg": "성공",
  "data": {
    "member": {
      "id": 2,
      "createDate": [
        2022,
        11,
        3,
        17,
        3,
        21,
        959430000
      ],
      "modifyDate": [
        2022,
        11,
        3,
        17,
        6,
        11,
        429765000
      ],
      "username": "user2",
      "email": "user2@test.com",
      "emailVerified": false,
      "nickname": "홍길순"
    }
  },
  "fail": false,
  "success": true
}
```
