### ISSUE TITLE
First Week Dev-Refactor

### ISSUE THREAD

**Issue by zuminzi** [likelion-backendschool/FinalProject_JuMinJi_team7#6]
### Todo
- [x] application.yml에서 개인정보(username, password 등)는 별도의 application-base-addi.yml 파일로 분리하기 (+ .gitignore에 추가)
- [x] EmailService에서 설정 관련 변수들은 .yml에서 읽어오기
- [x] EmailService에서 설정 관련 코드들은 EmailConfig로 책임 분리하기
- [x] DB 성능 개선을 위해 @Transactional Service의 update(수정, 삭제) 메서드에서 불필요한 save() 제거 (https://stackoverflow.com/questions/61460187/transactional-spring-jpa-save-not-necessary)
- [x] 서비스 레이어에 DB관련 서비스와 DB 관련되지 않은 서비스 구분하여 전자에 @Transactional 적용 후, 읽기 전용(read only) 트랜잭션과 그렇지 않은 트랜잭션 구분하여 어노테이션 적용하여 읽기 전용 성능 쿼리 최적화 (https://velog.io/@gongel/Spring-Transactional-annotation-%ED%99%9C%EC%9A%A9)
- [x] API 명세서대로 URI 수정하여 반영
- [x] 회원가입 뷰에서 필수 기재사항과 선택 기재사항 안내 추가
- [x] 회원가입 시 확인용 비밀번호 추가로 요청해서 비교 후 회원가입 처리 (view, dto, controller 수정 작업 필요)
- [x] 회원가입 폼 컬럼별로 적절한 @Valid 적용되도록 수정(ex.@Email,  @Min, @Max) 
(https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/package-summary.html)
- [x] home.html를 home/main.html으로 상위 디렉토리를 추가적으로 두어 상위폴더 내에 있는 뷰파일도 레이아웃 파일 내 부트스트랩 소스파일 경로(../)가 공통적으로 적용되도록 수정
- [x] GrandAuthority 로직 수정
- [x] 사용자 정보 수정 후 세션 업데이트
- [x] 아이디 찾기 구현 (요구사항 분석 과정에서 놓친 부분)
- [x] BindingResult를 통해 @Valid를 통한 유효성 검사 예외 처리 추가 (https://velog.io/@qotndus43/valid)
- [ ] 예외처리 리팩토링
- [ ] 아이디, 닉네임 중복 확인
- [ ] 1Week_Record.md 수정
